export enum GlobalMutationTypesEnum {
	// Notifications
	SET_PUSH_NOTIFICATIONS_ENABLED = 'SET_PUSH_NOTIFICATIONS_ENABLED',
	SET_EMAIL_NOTIFICATIONS_ENABLED = 'SET_EMAIL_NOTIFICATIONS_ENABLED',
	SET_ACTIVITY_NOTIFICATION_STATE = 'SET_ACTIVITY_NOTIFICATION_STATE',

	// Navigation
	NAVIGATE_TO_FEATURE = 'NAVIGATE_TO_FEATURE'
}
