// Load Lists
export const MUTATION_SET_TIME_FREQUENCIES = 'MUTATION_SET_TIME_FREQUENCIES';
export const MUTATION_SET_ROUTINES = 'MUTATION_SET_ROUTINES';
export const MUTATION_SET_ACTIVITIES = 'MUTATION_SET_ACTIVITIES';
export const MUTATION_SET_ACTIVITY_CATEGORIES = 'MUTATION_SET_ACTIVITY_CATEGORIES';
export const MUTATION_SET_ICONS = 'MUTATION_SET_ICONS';

// Routine CRUD
export const MUTATION_ADD_ROUTINE = 'MUTATION_ADD_ROUTINE';
export const MUTATION_DELETE_ROUTINE = 'MUTATION_DELETE_ROUTINE';
export const MUTATION_UPDATE_ROUTINE = 'MUTATION_UPDATE_ROUTINE';
export const MUTATION_CLEAR_ROUTINES = 'MUTATION_CLEAR_ROUTINES';

// Activities
export const MUTATION_ADD_ACTIVITY = 'MUTATION_CREATE_ACTIVITY';
export const MUTATION_DELETE_ACTIVITY = 'MUTATION_DELETE_ACTIVITY';
export const MUTATION_UPDATE_ACTIVITY = 'MUTATION_UPDATE_ACTIVITY';

// Focusing Items
export const MUTATION_SET_ACTIVE_ROUTINE = 'MUTATION_SET_ACTIVE_ROUTINE';
export const MUTATION_SET_ACTIVE_ACTIVITY = 'MUTATION_SET_ACTIVE_ACTIVITY';
export const MUTATION_SET_ACTIVE_ACTIVITY_ICON_BUTTON = 'MUTATION_SET_ACTIVE_ACTIVITY_ICON_BUTTON';

// Routine Board
export const MUTATION_RESET_ROUTINE_BOARD = 'MUTATION_RESET_ROUTINE_BOARD';
export const MUTATION_ASSIGN_ACTIVITY_TO_CELL = 'MUTATION_ASSIGN_ACTIVITY_TO_CELL';
export const MUTATION_CLEAR_ACTIVITY_FROM_CELL = 'MUTATION_CLEAR_ACTIVITY_FROM_CELL';

// Modal and Loading States
export const MUTATION_TOGGLE_TIME_SETTINGS_MODAL = 'MUTATION_TOGGLE_TIME_SETTINGS_MODAL';
export const MUTATION_TOGGLE_DELETE_ROUTINE_PROMPT = 'MUTATION_TOGGLE_DELETE_ROUTINE_PROMPT';
export const MUTATION_TOGGLE_CREATE_ACTIVITY_MODAL = 'MUTATION_TOGGLE_CREATE_ACTIVITY_MODAL';
export const MUTATION_TOGGLE_ROUTINE_STATISTICS_MODAL = 'MUTATION_TOGGLE_ROUTINE_STATISTICS_MODAL';
export const MUTATION_TOGGLE_LOADING_STATE = 'MUTATION_TOGGLE_LOADING_STATE';

// HTML Element Setters
export const MUTATION_SET_ROUTINE_PAGE_ZONE = 'MUTATION_SET_ROUTINE_PAGE_ZONE';
