// Load Lists
export const ACTION_SET_TIME_FREQUENCIES = 'ACTION_SET_TIME_FREQUENCIES';
export const ACTION_SET_ROUTINES = 'ACTION_SET_ROUTINES';
export const ACTION_SET_ACTIVITIES = 'ACTION_SET_ACTIVITIES';
export const ACTION_SET_ACTIVITY_CATEGORIES = 'ACTION_SET_ACTIVITY_CATEGORIES';
export const ACTION_SET_ICONS = 'ACTION_SET_ICONS';

// Routine
export const ACTION_ADD_ROUTINE = 'ACTION_ADD_ROUTINE';
export const ACTION_DELETE_ROUTINE = 'ACTION_DELETE_ROUTINE';
export const ACTION_UPDATE_ROUTINE = 'ACTION_UPDATE_ROUTINE';
export const ACTION_CLEAR_ROUTINES = 'ACTION_CLEAR_ROUTINES';

// Activities
export const ACTION_ADD_ACTIVITY = 'ACTION_CREATE_ACTIVITY';
export const ACTION_DELETE_ACTIVITY = 'ACTION_DELETE_ACTIVITY';
export const ACTION_UPDATE_ACTIVITY = 'ACTION_UPDATE_ACTIVITY';

// Focusing Items
export const ACTION_SET_ACTIVE_ROUTINE = 'ACTION_SET_ACTIVE_ROUTINE';
export const ACTION_SET_ACTIVE_ACTIVITY = 'ACTION_SET_ACTIVE_ACTIVITY';
export const ACTION_SET_ACTIVE_ACTIVITY_ICON_BUTTON = 'ACTION_SET_ACTIVE_ACTIVITY_ICON_BUTTON';

// Routine Board
export const ACTION_RESET_ROUTINE_BOARD = 'ACTION_RESET_ROUTINE_BOARD';
export const ACTION_ASSIGN_ACTIVITY_TO_CELL = 'ACTION_ASSIGN_ACTIVITY_TO_CELL';
export const ACTION_CLEAR_ACTIVITY_FROM_CELL = 'ACTION_CLEAR_ACTIVITY_FROM_CELL';

// Modal and Loading States
export const ACTION_TOGGLE_TIME_SETTINGS_MODAL = 'ACTION_TOGGLE_TIME_SETTINGS_MODAL';
export const ACTION_TOGGLE_DELETE_ROUTINE_PROMPT = 'ACTION_TOGGLE_DELETE_ROUTINE_PROMPT';
export const ACTION_TOGGLE_CREATE_ACTIVITY_MODAL = 'ACTION_TOGGLE_CREATE_ACTIVITY_MODAL';
export const ACTION_TOGGLE_ROUTINE_STATISTICS_MODAL = 'ACTION_TOGGLE_ROUTINE_STATISTICS_MODAL';
export const ACTION_TOGGLE_LOADING_STATE = 'ACTION_TOGGLE_LOADING_STATE';

// HTML Element Setters
export const ACTION_SET_ROUTINE_PAGE_ZONE = 'ACTION_SET_ROUTINE_PAGE_ZONE';
