export enum ActivityEnum {
	Shower = 'Shower',
	Bath = 'Bath',
	Sleep = 'Sleep',
	Nap = 'Nap',
	Eat = 'Eat',
	Breakfast = 'Breakfast',
	Lunch = 'Lunch',
	Dinner = 'Dinner',
	ApplyMakeUp = 'Apply Make-up',
	StyleHair = 'Style Hair',
	OralHealth = 'Oral Health',

	Cooking = 'Cooking',
	CleanHouse = 'Clean House',
	Vacuum = 'Vacuum',
	Laundry = 'Laundry',
	WashDishes = 'Wash Dishes',
	CleanWindows = 'Clean Windows',
	PolishSurfaces = 'Polish Surfaces',

	Running = 'Running',
	Swimming = 'Swimming',
	Cycling = 'Cycling',
	Golf = 'Golf',
	Cricket = 'Cricket',
	Sailing = 'Sailing',
	Gym = 'Gym',
	Hiking = 'Hiking',

	FamilyWalk = 'Family Walk',
	BoardGames = 'Board Games',
	WatchFamilyMovie = 'Watch a Family Movie',

	Study = 'Study',
	Homework = 'Homework',
	Test = 'Test',
	Project = 'Project',
	StudyGroup = 'Study Group',

	WatchTv = 'Watch TV',
	WatchMovie = 'Watch Movie',
	PlayGames = 'Play Games',
	Socialize = 'Socialize',
	PlayGamesWithFriends = 'Play Games with Friends',
	Braai = 'Braai',
	Barbecue = 'Barbecue',
	Party = 'Party',

	GroceryShopping = 'Grocery Shopping',
	PharmaceuticalShopping = 'Pharmaceutical Shopping',
	HobbyShopping = 'Hobby Shopping',
	ClothingShopping = 'Clothing Shopping',
	SuppliesShopping = 'Supplies Shopping',
	InventoryManagement = 'Inventory Management',
	ShoppingForKids = 'Shopping for Kids'
}
